version: "3.1"

services:
  w3schools-db:
    image: biarms/mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: w3schools
      MYSQL_USER: feusi
      MYSQL_PASSWORD: feusi
    volumes:
      - ./data/mysql-arm:/var/lib/mysql
      - ./init-mysql:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"

  rest-api:
    build: ./rest-api
    restart: always
    depends_on:
      - w3schools-db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: w3schools-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: w3schools
